const prosperity = [
  'Bank',
  'Bishop',
  'City',
  'Contraband',
  'Counting House',
  'Expand',
  'Forge',
  'Goons',
  'Grand Market',
  'Hoard',
  'King\'s Court',
  'Loan',
  'Monument',
  'Mountebank',
  'Mint',
  'Rabble',
  'Royal Seal',
  'Quary',
  'Peddler',
  'Talisman',
  'Trade Route',
  'Vault',
  'Venture',
  'Watchtower',
  'Worker\'s Village',
];

const darkAges = [
  'Altar',
  'Armory',
  'Band of Misfits',
  'Bandit Camp',
  'Beggar',
  'Catacombs',
  'Count',
  'Counterfeit',
  'Cultist',
  'Death Cart',
  'Feodum',
  'Forager',
  'Fortress',
  'Hermit',
  'Graverobber',
  'Hunting Grounds',
  'Ironmonger',
  'Junk Dealer',
  'Knights',
  'Market Square',
  'Marauder',
  'Mystic',
  'Pillage',
  'Poor House',
  'Procession',
  'Rats',
  'Rebuild',
  'Rogue',
  'Sage',
  'Scavenger',
  'Squire',
  'Storeroom',
  'Urchin',
  'Vagrant',
  'Wandering Minstrel'];

const dominion = [
  'Cellar',
  'Chapel',
  'Moat',
  'Harbinger',
  'Village',
  'Merchant',
  'Workshop',
  'Bureaucrat',
  'Vassal',
  'Gardens',
  'Militia',
  'Moneylender',
  'Remodel',
  'Smithy',
  'Bandit',
  'Poacher',
  'Throne Room',
  'Council Room',
  'Festival',
  'Laboratory',
  'Library',
  'Market',
  'Mine',
  'Witch',
  'Sentry',
  'Artisan',
];

const hinterlands = [
  'Crossroads',
  'Duchess',
  'Fools Gold',
  'Develop',
  'Oasis',
  'Oracle',
  'Scheme',
  'Tunnel',
  'Jack of all Trades',
  'Noble Brigand',
  'Nomad Camp',
  'Silk Road',
  'Spice Merchant',
  'Trader',
  'Cache',
  'Cartographer',
  'Embassy',
  'Haggler',
  'Highway',
  'Ill-Gotten Gains',
  'Inn',
  'Mandarin',
  'Margrave',
  'Stables',
  'Border Village',
  'Farmland'];

const intrigue = [
  'Courtyard',
  'Pawn',
  'Secret Chamber',
  'Great Hall',
  'Masquerade',
  'Shanty Town',
  'Steward',
  'Swindler',
  'Wishing Well',
  'Baron',
  'Bridge',
  'Conspirator',
  'Coppersmith',
  'Ironworks',
  'Mining Village',
  'Scout',
  'Duke',
  'Minion',
  'Saboteur',
  'Torturer',
  'Trading Post',
  'Tribute',
  'Upgrade',
  'Harem',
  'Nobles'];

const seaside = [
  'Embargo',
  'Haven',
  'Lighthouse',
  'Native Village',
  'Pearl Diver',
  'Ambassador',
  'Fishing Village',
  'Lookout',
  'Smugglers',
  'Warehouse',
  'Caravan',
  'Cutpurse',
  'Island',
  'Navigator',
  'Pirate Ship',
  'Salvager',
  'Sea Hag',
  'Treasure Map',
  'Bazaar',
  'Explorer',
  'Ghost Ship',
  'Merchant Ship',
  'Outpost',
  'Tactician',
  'Treasury',
  'Wharf'];

const guilds = [
  'Advisor',
  'Baker',
  'Butcher',
  'Candlestick Maker',
  'Doctor',
  'Herald',
  'Journeyman',
  'Masterpiece',
  'Merchant Guild',
  'Plaza',
  'Soothsayer',
  'Stonemason',
  'Taxman'];

const nocturne = [
  'Druid',
  'Faithful Hound',
  'Guardian',
  'Monastery',
  'Pixie',
  'Tracker',
  'Changeling',
  'Fool',
  'Ghost Town',
  'Leprechaun',
  'Night Watchman',
  'Secret Cave',
  'Bard',
  'Blessed Village',
  'Cemetery',
  'Conclave',
  'Devil\'s Workshop',
  'Exorcist',
  'Necromancer',
  'Shepherd',
  'Skulk',
  'Cobbler',
  'Crypt',
  'Cursed Village',
  'Den of Sin',
  'Idol',
  'Pooka',
  'Sacred Grove',
  'Tormentor',
  'Tragic Hero',
  'Vampire',
  'Werewolf',
  'Raider',
];

export const AllDecks = {
  DA: darkAges,
  DO: dominion,
  HI: hinterlands,
  IN: intrigue,
  SE: seaside,
  GU: guilds,
  NO: nocturne,
  PR: prosperity,
};

export const DeckNames = {
  'Dark Ages': 'DA',
  Dominion: 'DO',
  Hinterlands: 'HI',
  Intrigue: 'IN',
  Seaside: 'SE',
  Guilds: 'GU',
  Nocturn: 'NO',
  Prosperity: 'PR',
};

export const Dependencies = {
  'Bandit Camp': ['Spoils'],
  Cultist: ['Ruins'],
  'Death Cart': ['Ruins'],
  Hermit: ['Madman'],
  Marauder: ['Ruins', 'Spoils'],
  Pillage: ['Spoils'],
  Druid: ['Boons'],
  Pixie: ['Boons', 'Goat'],
  Tracker: ['Boons', 'Pouch'],
  Fool: ['Lost in the Woods', 'Boons', 'Lucky Coin'],
  Leprechaun: ['Wish', 'Hex'],
  'Secret Cave': ['Magic Lamp'],
  Bard: ['Boons'],
  'Blessed Village': ['Boons'],
  Cemetery: ['Haunted Mirror'],
  'Devil\'s Workshop': ['Imp'],
  Exorcist: ['Imp', 'Will o\' Wisp', 'Ghost'],
  Necromancer: ['Zombies'],
  Shepherd: ['Pasture'],
  Skulk: ['Hexes'],
  'Cursed Village': ['Hexes'],
  Idol: ['Boons', 'Curse'],
  Pooka: ['Cursed Gold'],
  'Sacred Grove': ['Boons'],
  Tormentor: ['Imp', 'Hexes'],
  Vampire: ['Hexes', 'Bat'],
  Werewolf: ['Hexes'],
};
